services:
  db:
    image: postgres:latest
    container_name: eldercare_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: elder-care-app
    container_name: eldercare_backend
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/elder_care_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
